name: Deploy to S3

on:
  push:
    branches:
      - Master  # Use the correct case for your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1  # Set your AWS region here
        env:
          AWS_DEFAULT_REGION: us-east-1  # Set your AWS region here

      - name: Fetch latest changes
        run: git fetch

      - name: List changed files
        run: |
          git diff --name-only HEAD^..HEAD > changed-files.txt

      - name: Delete changed files from S3
        run: |
          while read -r file; do
            aws s3 rm "s3://hypackelgames/$file"
          done < changed-files.txt

      - name: Upload new files to S3
        run: |
          git ls-files | xargs -I % aws s3 cp "%" "s3://hypackelgames/%" --acl public-read
