# name: Upload to S3

# on:
#   push:
#     branches:
#       - Master

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Install AWS CLI
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y python3-pip
#           pip3 install awscli --upgrade --user

#       - name: Configure AWS credentials
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         run: |
#           aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
#           aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
#           aws configure set default.region us-east-1

#       - name: Delete contents of github1 folder in S3
#         run: |
#           aws s3 rm s3://hypackelgames/ --recursive

#       - name: Upload files to S3
#         run: |
#           aws s3 cp . s3://hypackelgames/ --recursive